version: '3.8'

networks:
  coolstuff-enterprise-network:
    name: coolstuff-enterprise-network
    driver: bridge

volumes:
  mysqldata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/server/mysql/data'

services:
  idp:
    image: kenchan0130/simplesamlphp
    container_name: coolstuff-idp-service-provider
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://app.example.com
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost/simplesaml/module.php/saml/sp/saml2-acs.php/test-sp
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost/simplesaml/module.php/saml/sp/saml2-logout.php/test-sp
    ports:
      - 9002:8080
    networks:
      coolstuff-enterprise-network:
        aliases:
          - idp_service_provider

  admin_backend:
    image: nginx:1.21.6-alpine
    container_name: coolstuff-admin-nginx
    restart: unless-stopped
    ports:
      - "9001:80"
    volumes:
      - ./src:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      coolstuff-enterprise-network:
        aliases:
          - admin_backend

  admin:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: coolstuff-admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: develop,debug,coverage
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
      PHP_IDE_CONFIG: docker
    volumes:
      - ./src:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      coolstuff-enterprise-network:
        aliases:
          - admin

  mysql:
    image: mysql:8.0
    container_name: coolstuff-admin-rdbms
    environment:
      MYSQL_ROOT_PASSWORD: '$${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '$${DB_DATABASE}'
      MYSQL_USER: '$${DB_USERNAME}'
      MYSQL_PASSWORD: '$${DB_PASSWORD}'
    ports:
      - "9006:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      coolstuff-enterprise-network:
        aliases:
          - admin_mysql

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: coolstuff-rdbms-admin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "9004:80"
    networks:
      coolstuff-enterprise-network:
        aliases:
          - db-admin

  mailhog:
    image: mailhog/mailhog:latest
    container_name: coolstuff-smtp
    ports:
      - "8025:1025"
      - "9005:8025"
    networks:
      coolstuff-enterprise-network:
        aliases:
            - mailhog

  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    container_name: coolstuff-broadcaster
    environment:
      SOKETI_DEBUG: '1'
      SOKETI_METRICS_SERVER_PORT: '9601'
      SOKETI_DEFAULT_APP_ID: '$${PUSHER_APP_ID}'
      SOKETI_DEFAULT_APP_KEY: '$${PUSHER_APP_KEY}'
      SOKETI_DEFAULT_APP_SECRET: '$${PUSHER_APP_SECRET}'
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    networks:
      coolstuff-enterprise-network:
        aliases:
            - soketi