name: CoolStuff Enteprise QA Pipeline
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    env:
      DB_DATABASE: coolstuff_test_db
      DB_CONNECTION: mysql
      DB_USERNAME: testing
      DB_PASSWORD: t3st!n6
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis

    # Service container Mysql mysql
    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

      # Label used to access the service container
      mysql:
        # Docker Hub image (also with version)
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE:  coolstuff_test_db
          MYSQL_USER: testuser
          MYSQL_PASSWORD: t3st!n6
        ## map the "external" 33306 port with the "internal" 3306
        ports:
          - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [ '8.2','8.1' ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install PHP versions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migrations
        # Set environment
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: coolstuff_test_db
          DB_PORT: 33306
          DB_USER: testing
          DB_PASSWORD: t3st!n6
        run: php artisan migrate

      - name: Show current dir
        run: pwd

      - name: PHP Version
        run: php --version

      # Code quality
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        # Set environment
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: coolstuff_test_db
          DB_PORT: 33306
          DB_USER: testing
          DB_PASSWORD: t3st!n6

        run: vendor/bin/phpunit --testdox